### ISSUE TITLE
Build fails on macOS Beta

### ISSUE THREAD

**Issue by VKoskiv** [gfx-rs/gfx-ocean#10]
Could totally just be my beta build, but just in case it's a macOS problem:

OS: macOS 10.14 Mojave Beta (Darwin 18.0.0)

https://pastebin.com/wKpR3EST

Command used: `cargo run --features metal`¨

Please let me know if you need more details/testing help!

**Comment by msiglreith** [comment]
Thanks for the report. I probably should update to the latest master and hope it gets fixed on the way.
Currently unable to test it due to lack of hardware access.

**Comment by yerke** [comment]
I just compiled it successfully on macOS Mojave 10.14.6, so I believe this issue can be closed.
One question though: Is this how it is supposed to look like?
<img width="1204" alt="Screen Shot 2020-03-24 at 12 22 30 AM" src="https://user-images.githubusercontent.com/5137691/77399057-d9b71400-6d65-11ea-991e-7165d8e84cb6.png">

**Comment by kvark** [comment]
@yerke the startup camera could be closer to the ocean, but you can fly and rotate it to get a better look.
The original issue is fixed by #18
