### ISSUE TITLE
No suitable WSI enabled

### ISSUE THREAD

**Issue by rofrol** [gfx-rs/gfx-ocean#16]
```bash
$ cargo run --features vulkan
...
     Running `target/debug/ocean`
thread 'main' panicked at 'No suitable WSI enabled!', /home/roman/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-backend-vulkan-0.3.3/src/window.rs:305:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Ubuntu 19.10 X11 nVidia

**Comment by kvark** [comment]
Would be good to update this to use gfx-hal 0.4 with raw-window-handle WSI contract.

**Comment by msiglreith** [comment]
Thanks for the report, I'm looking into porting over to 0.4 atm

**Comment by msiglreith** [comment]
Update now in master, I will try to test it on unix as well

**Comment by kvark** [comment]
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnsupportedWindowHandle', src/libcore/result.rs:1165:5

**Comment by kvark** [comment]
Perhaps we could update winit to 0.20 here?

**Comment by msiglreith** [comment]
Thanks for testing, updated it to 0.20 even though I'm not sure if it did it ideally, harder than expected 👀

**Comment by kvark** [comment]
Ok, so the original issue is simply the fact `x11` support became optional in Vulkan backend :)
having `features = ["x11"]` solves it for linux.

However, something w.r.t. winit events is broken, since there appears to be a huge lag. Perhaps, you are trying to render every time there is an event?

**Comment by msiglreith** [comment]
yeah, I only issue draws on redraw requests now. I hope this helps.

**Comment by kvark** [comment]
controls are fixed! :tada: but the `x11` feature is still missing from the cargo manifest

**Comment by msiglreith** [comment]
`x11` has been added - closing
